# Author: Jonny Langefeld
# Docker Version: 1.13.0
# Docker Compose Version: 1.10.1
#

version: "3"

services:
    web1:
        image: dockercloud/hello-world
        container_name: web1
        ports:
            - "81:80"

    web2:
        image: dockercloud/hello-world
        container_name: web2
        ports:
            - "82:80"

    apache:
        build: ./apache
        container_name: apache
        ports:
            - "80:80"
            - "443:443"
