# Author: Jonny Langefeld
# Docker Version: 1.13.0
# Docker Compose Version: 1.10.1
#

version: "3"

services:
    web1:
        image: dockercloud/hello-world
        container_name: web1
        ports:
            - "81:80"

    web2:
        image: dockercloud/hello-world
        container_name: web2
        ports:
            - "82:80"

    haproxy:
        build: ./haproxy
        container_name: haproxy
        volumes:
            - logging:/sidecar
            - certs:/localcert
        environment:
            USE_LOCAL_CERT: ${USE_LOCAL_CERT:-false}
            GEN_CERT: ${GEN_CERT:-true}
            EMAIL: ${EMAIL:-jonathan.langefeld@smart-energy.de}
            EXTERNAL_URL: ${EXTERNAL_URL:-docker-test.energy-smart.de}
        ports:
            - "80:80"
            - "443:443"

    syslog-sidecar:
        build: ./logging
        container_name: logging
        volumes:
            - logging:/sidecar

volumes:
    logging:
    certs:
